# Generated by Django 6.0.6 on 2026-10-02 02:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
        ('products', '0003_product_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='5 letters, A–Z. Locked once a customer has used it.', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{5}$', 'Codes are exactly 5 letters, A–Z.')])),
                ('name', models.CharField(blank=True, help_text='For staff only, e.g. “Fall 2026”.', max_length=100, verbose_name='Promotion')),
                ('percent_off', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percent off')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Optional — empty means now.', null=True, verbose_name='Starts')),
                ('ends_at', models.DateTimeField(help_text='The code stops working here.', verbose_name='Ends')),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to retire the code early.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, help_text='Leave empty to discount the whole order.', related_name='coupons', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ends_at', 'code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.coupon'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('coupon__isnull', False)), fields=('coupon', 'user'), name='coupon_once_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('percent_off__gte', 1), ('percent_off__lte', 100)), name='coupon_percent_1_to_100'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('starts_at__lt', models.F('ends_at')), _connector='OR'), name='coupon_starts_before_it_ends'),
        ),
    ]
